export function initImageViewer(){
 const viewer=document.createElement('dialog');viewer.id='image-viewer';viewer.setAttribute('aria-labelledby','image-viewer-title');
 viewer.innerHTML=`<header class="image-viewer-bar"><strong id="image-viewer-title">Imagen ampliada</strong><div><button type="button" data-zoom="out" aria-label="Alejar imagen">−</button><output id="image-zoom" aria-live="polite">100 %</output><button type="button" data-zoom="in" aria-label="Acercar imagen">+</button><button type="button" data-zoom="fit">Ajustar</button><button type="button" data-zoom="close" aria-label="Cerrar imagen ampliada">×</button></div></header><div class="image-viewport" tabindex="0" aria-label="Imagen ampliada. Rueda para ampliar, arrastra para desplazar. Flechas para mover y signos más o menos para zoom."><img draggable="false" alt=""></div><p class="image-viewer-help">Rueda o + / − para ampliar · Arrastra para moverte · Doble clic para ampliar · Esc para cerrar</p>`;
 document.body.append(viewer);
 const stage=viewer.querySelector('.image-viewport'),img=stage.querySelector('img'),output=viewer.querySelector('output');let scale=1,fit=1,x=0,y=0,opener;
 const pointers=new Map();let gesture=null;
 function paint(){const boundX=Math.max(0,(img.naturalWidth*scale-stage.clientWidth)/2),boundY=Math.max(0,(img.naturalHeight*scale-stage.clientHeight)/2);x=Math.max(-boundX,Math.min(boundX,x));y=Math.max(-boundY,Math.min(boundY,y));img.style.transform=`translate(-50%,-50%) translate(${x}px,${y}px) scale(${scale})`;output.value=Math.round(scale/fit*100)+' %';}
 function reset(){if(!img.naturalWidth||!stage.clientWidth)return;fit=Math.min(stage.clientWidth/img.naturalWidth,stage.clientHeight/img.naturalHeight)*.96;scale=fit;x=y=0;paint();}
 function zoom(factor,px=0,py=0){const next=Math.max(fit,Math.min(fit*8,scale*factor)),ratio=next/scale;x=px-(px-x)*ratio;y=py-(py-y)*ratio;scale=next;paint();}
 img.onload=reset;img.onerror=()=>{viewer.querySelector('.image-viewer-help').textContent='No se pudo cargar la imagen. Cierra el visor e inténtalo de nuevo.'};
 function open(link){opener=link;const preview=link.querySelector('img');viewer.querySelector('strong').textContent=preview?.alt||'Imagen de referencia · Tívoli';img.alt=preview?.alt||'Imagen de referencia de Tívoli';img.removeAttribute('src');img.src=link.href;viewer.showModal();if(img.complete)reset();stage.focus();}
 document.querySelectorAll('a[href]').forEach(link=>{if(/\.(png|jpe?g|webp)(\?.*)?$/i.test(link.getAttribute('href'))&&new URL(link.href).origin===location.origin){link.classList.add('enlarge-image');link.setAttribute('aria-haspopup','dialog');link.title='Ampliar imagen';if(link.querySelector('img')){const hint=document.createElement('span');hint.className='enlarge-image-hint';hint.textContent='⤢ Ampliar imagen';link.append(hint);}}});
 document.addEventListener('click',e=>{const link=e.target.closest('a[href]');if(!link||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;if(/\.(png|jpe?g|webp)(\?.*)?$/i.test(link.getAttribute('href'))&&new URL(link.href).origin===location.origin){e.preventDefault();open(link);}});
 viewer.querySelector('[data-zoom="close"]').onclick=()=>viewer.close();viewer.querySelector('[data-zoom="fit"]').onclick=reset;viewer.querySelector('[data-zoom="in"]').onclick=()=>zoom(1.4);viewer.querySelector('[data-zoom="out"]').onclick=()=>zoom(1/1.4);
 viewer.addEventListener('close',()=>{pointers.clear();gesture=null;opener?.focus();});
 stage.addEventListener('wheel',e=>{e.preventDefault();const r=stage.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2);},{passive:false});
 stage.addEventListener('dblclick',e=>{const r=stage.getBoundingClientRect();zoom(1.8,e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2);});
 function snapshot(){const p=[...pointers.values()];gesture=p.length===2?{distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),cx:(p[0].x+p[1].x)/2,cy:(p[0].y+p[1].y)/2}:p.length?{cx:p[0].x,cy:p[0].y}:null;}
 stage.onpointerdown=e=>{stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});snapshot();stage.classList.add('dragging');};
 stage.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=gesture;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});snapshot();if(!old||!gesture)return;x+=gesture.cx-old.cx;y+=gesture.cy-old.cy;if(old.distance&&gesture.distance){const r=stage.getBoundingClientRect();zoom(gesture.distance/old.distance,gesture.cx-r.left-r.width/2,gesture.cy-r.top-r.height/2);}else paint();};
 function release(e){pointers.delete(e.pointerId);snapshot();if(!pointers.size)stage.classList.remove('dragging');}stage.onpointerup=release;stage.onpointercancel=release;
 stage.onkeydown=e=>{if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','0'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoom(1.4);if(e.key==='-')zoom(1/1.4);if(e.key==='0')reset();if(e.key==='ArrowLeft')x+=60;if(e.key==='ArrowRight')x-=60;if(e.key==='ArrowUp')y+=60;if(e.key==='ArrowDown')y-=60;paint();};
 new ResizeObserver(()=>{if(viewer.open)reset();}).observe(stage);
}
