import {rideMotion} from './ride-motion.js';
import {installFlight} from './flight.js';
import {frontageAlignment} from './frontage.js';
import {buildCablecar} from './cablecar.js';
import {buildProposal} from './proposal.js';
import {loadTerrain} from './terrain.js';
import {buildExisting} from './existing.js';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const COLORS={park:0x80b694,commercial:0xdaaa70,hotel:0xb597c9,green:0x4d8a69,parking:0x94a3af,current:0xb77954,boundary:0x287d76};
export async function createWorld(host,onSelect){
 const terrain=await loadTerrain();const scene=new THREE.Scene(); scene.background=new THREE.Color('#e7ece6');
 const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1; host.appendChild(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(40,1,1,5000); const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=35;controls.maxDistance=1600;
 const hemi=new THREE.HemisphereLight(0xfffbef,0xa5b9a2,2.3);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff4dc,1.8);sun.position.set(-250,550,200);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-500,right:500,top:500,bottom:-500,far:1300});sun.shadow.bias=-.00035;sun.shadow.normalBias=.35;scene.add(sun);
 const base=new THREE.Group(),current=new THREE.Group(),future=new THREE.Group();scene.add(base,current,future);const groups={base,current,future};let mode='future',labels=true,attractionNames=true,night=false,parking=false,selected=null;
 const labelItems=[],pickables=[],animated=[];const matCache=new Map();
 function mat(c){if(!matCache.has(c))matCache.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.85}));return matCache.get(c)}
 function mesh(g,geo,c,x=0,y=0,z=0,id){const m=new THREE.Mesh(geo,mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;if(id){m.userData.zone=id;pickables.push(m)}g.add(m);return m}
 function box(g,x,y,z,w,h,d,c,id){const m=mesh(g,new THREE.BoxGeometry(w,h,d),c,x,y+h/2,z,id);if(h<=.8)m.userData.drape=true;return m}
 function cyl(g,x,y,z,r,h,c,id,r2=r){return mesh(g,new THREE.CylinderGeometry(r2,r,h,16),c,x,y+h/2,z,id)}
 function poly(g,pts,c,h=1,y=0,id){const s=new THREE.Shape();pts.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();let geo=new THREE.ExtrudeGeometry(s,{depth:h,bevelEnabled:false});geo.rotateX(-Math.PI/2);const m=mesh(g,geo,c,0,y,0,id);m.userData.drape=h<=1.2&&y<2;return m}
 function line(g,pts,c,width=1,y=2,dashed=false){const vs=pts.map(p=>new THREE.Vector3(p[0],p[1]??y,p[2]??p[1]));const geo=new THREE.BufferGeometry().setFromPoints(vs);const m=new THREE.Line(geo,dashed?new THREE.LineDashedMaterial({color:c,dashSize:5,gapSize:3}):new THREE.LineBasicMaterial({color:c}));m.computeLineDistances();g.add(m);return m}
 function ribbon(g,pts,width,c,y=.6,id){for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz);if(l<.1)continue;const o=box(g,(a[0]+b[0])/2,y,(a[1]+b[1])/2,width,.22,l,c,id);o.rotation.y=Math.atan2(dx,dz)}}
 function outline(g,pts,c,y=3,dash=false){const p=[...pts,pts[0]].map(([x,z])=>[x,y,z]);line(g,p,c,1,y,dash);if(!dash)ribbon(g,[...pts,pts[0]],1.15,c,y);else{for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length],dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz);for(let d=0;d<l;d+=11){const t=Math.min(d+6,l),q=box(g,a[0]+dx*(d+t)/2/l,y,a[1]+dz*(d+t)/2/l,1.6,.1,t-d,c);q.rotation.y=Math.atan2(dx,dz);q.material=mat(c).clone();q.material.depthTest=false;q.renderOrder=100;}}}}
 function label(g,text,x,z,y=8,kind='zone',id){const el=document.createElement('button');el.className='map-label '+kind;el.textContent=text;el.type='button';el.tabIndex=id?0:-1;if(id)el.onclick=()=>onSelect(id);else el.style.pointerEvents='none';host.appendChild(el);const twin=el.cloneNode(true);twin.onclick=el.onclick;host.appendChild(twin);labelItems.push({el,twin,p:new THREE.Vector3(x,y,z),g,kind,id});return el}
 function tree(g,x,z,y=1,s=1){cyl(g,x,y,z,.45*s,4*s,0x80735b);mesh(g,new THREE.IcosahedronGeometry(3.3*s,1),0x5e9473,x,y+6*s,z)}
 function palm(g,x,z,y=1){cyl(g,x,y,z,.4,7,0xa49170);for(let i=0;i<6;i++){const leaf=mesh(g,new THREE.ConeGeometry(1.1,6,4),0x438368,x,y+8,z);leaf.rotation.z=1.05;leaf.rotation.y=i*Math.PI/3}}
 function building(g,p,h,c,id){const m=poly(g,p,c,h,1,id);return m}
 function windows(g,x,z,w,d,h,y=1,c=0x658c92){for(let a=-w/2+3;a<w/2;a+=6)for(let v=3;v<h-1;v+=4){box(g,x+a,y+v,z+d/2+.1,2,1.8,.2,c);box(g,x+a,y+v,z-d/2-.1,2,1.8,.2,c)}}
 function pavilion(g,x,z,y,s=1){box(g,x,y,z,12*s,6*s,9*s,0xf3e7ce,'park');const roof=mesh(g,new THREE.ConeGeometry(10*s,4*s,4),0xb86e55,x,y+8*s,z);roof.rotation.y=Math.PI/4;for(let i=-1;i<=1;i++)box(g,x+i*3*s,y+1,z+4.6*s,1.8*s,3*s,.2,0x365d61)}
 function wheel(g,x,z,y,r=17){const sub=new THREE.Group();g.add(sub);sub.position.set(x,y+r+3,z);for(let i of [-1,1]){const leg=box(g,x+i*5,y,z,1.2,r+3,1.2,0xe9d9b9,'park');leg.rotation.z=i*.27}const rot=new THREE.Group();sub.add(rot);const tor=mesh(rot,new THREE.TorusGeometry(r,.65,6,60),0xe3b959);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;line(rot,[[0,0,0],[Math.cos(a)*r,Math.sin(a)*r,0]],0xf3e6bd);cyl(rot,Math.cos(a)*r,Math.sin(a)*r-1,0,1.7,2.4,i%2?0xe39b70:0x5c9c97)}animated.push({o:rot,type:'wheel',g});}
 function carousel(g,x,z,y,r=10){cyl(g,x,y,z,r,1,0xf0d7a6,'park');cyl(g,x,y,z,.9,8,0xd3a05e);mesh(g,new THREE.ConeGeometry(r+1,5,20),0xc4775c,x,y+10,z);for(let i=0;i<10;i++){const a=i*Math.PI/5; cyl(g,x+Math.cos(a)*(r-2),y+1,z+Math.sin(a)*(r-2),.2,7,0xdcb26e);box(g,x+Math.cos(a)*(r-2),y+2.5,z+Math.sin(a)*(r-2),2.6,1.5,1,0xede1c2)}}
 function coaster(g,x,z,y,s=1){const pts=[];for(let i=0;i<24;i++){const a=i/24*Math.PI*2;pts.push(new THREE.Vector3(x+Math.cos(a)*30*s,y+4+(Math.sin(a*2)+1)*8*s,z+Math.sin(a)*18*s))}const curve=new THREE.CatmullRomCurve3(pts,true);mesh(g,new THREE.TubeGeometry(curve,150,.8,5,true),0xc27c53,0,0,0,'park');for(let i=0;i<24;i+=2){const p=pts[i];cyl(g,p.x,y,p.z,.45,p.y-y,0xa9b0a0)}const train=box(g,0,0,0,3,2,5,0xe4b55b,'park');animated.push({o:train,type:'train',curve,g,motion:rideMotion(curve,{min:2,max:14,gravity:7,drag:.25})});}
 function car(g,x,z,y,c=0xeee7d9){box(g,x,y,z,2,1.1,4,c);box(g,x,y+1,z,1.6,.65,2,0x719195)}
 function parkingLot(g,cx,cz,w,d,y=1,underground=false){box(g,cx,y-.6,cz,w,.6,d,underground?0x677d89:0xb8b8aa,'parking');for(let x=cx-w/2+4;x<cx+w/2-3;x+=5)for(let z=cz-d/2+5;z<cz+d/2-3;z+=12){box(g,x,y+.02,z,.15,.08,5,0xe8e5d5);if(Math.sin(x+z)>.1)car(g,x+2,z,y+.2,Math.sin(x)>0?0xdbbda1:0x7f9592)}}
 let context=await fetch('/context.json').then(r=>r.ok?r.json():null).catch(()=>null);let plan=await fetch('/plan.json').then(r=>r.ok?r.json():null).catch(()=>null);
 if(!context||!plan)throw new Error('No se pudieron cargar las bases cartográficas locales.');
 const frontage=frontageAlignment(context.roads);
 terrain.ground(base);
 if(context){for(const r of context.roads){ribbon(base,r.points,r.kind==='footway'?3:10,0xf6f2e8,-.35);ribbon(base,r.points,r.kind==='footway'?1.8:7,0xb3b9b2,-.1)}for(const b of context.buildings||[]){const c=b.points.reduce((s,p)=>[s[0]+p[0]/b.points.length,s[1]+p[1]/b.points.length],[0,0]);let isin=false;for(let i=0,j=plan.oldBoundary.length-1;i<plan.oldBoundary.length;j=i++){const a=plan.oldBoundary[i],d=plan.oldBoundary[j];if((a[1]>c[1])!==(d[1]>c[1])&&c[0]<(d[0]-a[0])*(c[1]-a[1])/(d[1]-a[1])+a[0])isin=!isin;}if(!isin&&Math.hypot(c[0]-89.41,c[1]-196.33)>18)building(base,b.points,Math.min(b.height||9,26),0xd8d9ca);}const seen=new Set();const rankedRoads=[...context.roads].sort((a,b)=>{const score=r=>Math.min(...r.points.map(p=>Math.hypot(p[0]-70,p[1]+20)));return score(a)-score(b)});for(const r of rankedRoads){if(!r.name||seen.has(r.name)||r.points.length<2)continue;seen.add(r.name);const p=r.points[Math.floor(r.points.length/2)];if(Math.hypot(p[0]-60,p[1]+20)<410)label(base,r.name,p[0],p[1],3,'street')}for(const p of (context.landmarks||[]).filter(p=>p.kind!=='theatre'&&p.kind!=='cable'))label(p.kind==='theatre'?current:base,p.name,p.x,p.z,15,'landmark')}
 const old=plan?.oldBoundary||context?.parkBoundary||[[-120,-150],[80,-150],[90,160],[-140,100]];
 const bounds=plan?.boundary||[[-180,-240],[160,-240],[200,170],[-180,230]];
 const park=plan?.park||[[-130,-200],[65,-190],[65,-45],[-130,-35]];
 const commercial=plan?.commercial||[[-130,-20],[65,-35],[100,160],[-100,185]];
 const hotel=plan?.hotel||[[95,-25],[155,-25],[155,55],[95,55]];
 const utility=plan?.utility||[[95,-140],[165,-140],[165,-40],[95,-40]];
 const greens=plan?.greens||[[[-165,-220],[140,-220],[140,-195],[-165,-195]],[[170,-180],[195,-180],[200,120],[170,120]]];
 const midpoint=p=>{const sum=p.reduce((s,a)=>[s[0]+a[0],s[1]+a[1]],[0,0]);return sum.map(n=>n/p.length)};const pc=midpoint(park),cc=midpoint(commercial),hc=midpoint(hotel),uc=midpoint(utility);
 const ext=pts=>({minX:Math.min(...pts.map(p=>p[0])),maxX:Math.max(...pts.map(p=>p[0])),minZ:Math.min(...pts.map(p=>p[1])),maxZ:Math.max(...pts.map(p=>p[1]))});
 const inside=(x,z,pts)=>{let v=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if((a[1]>z)!=(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])v=!v}return v};
 function scatter(g,pts,y,density=22){const e=ext(pts);for(let x=e.minX+8;x<e.maxX-5;x+=density)for(let z=e.minZ+8;z<e.maxZ-5;z+=density){const xx=x+Math.sin(z*3+x)*5,zz=z+Math.cos(x)*5;if(inside(xx,zz,pts))tree(g,xx,zz,y,.65+(.5+.5*Math.sin(x*z))*.5)}}
 const existing=await buildExisting({group:current,terrain,mesh,box,cyl,poly,ribbon,line,label,old,inside});poly(future,park,0xb7bc96,1.2,0,'park');outline(future,park,0x397b57,1.5);
 // Both boundaries remain visible in both scenarios, so a change of mode never changes the geographical frame.
 const boundaryGroup=new THREE.Group();base.add(boundaryGroup);outline(boundaryGroup,bounds.map(frontage.boundary),COLORS.boundary,3,false);outline(boundaryGroup,old.map(frontage.boundary),COLORS.current,3.6,true);
 for(const [index,source] of greens.entries()){const p=index===2?source.map(frontage.green):source;poly(future,p,0x65a07c,1.1,0,'green');scatter(future,p,1,15)}
 const ce=ext(commercial);const proposal=await buildProposal({group:future,terrain,mesh,box,cyl,poly,ribbon,label,wheel,coaster,tree,alignFrontage:frontage.roof});
 // Existing public water facility remains a shared geographical reference.
 poly(base,utility,0xa7babc,1,0,'utility');box(base,uc[0],1,uc[1],30,9,25,0x94abae,'utility');cyl(base,uc[0]+24,1,uc[1],10,5,0xc5d4cd,'utility');
 const currentParking=plan?.currentParking;
 if(currentParking){poly(current,currentParking,0xb8b8aa,.5,0,'parking');const e=ext(currentParking),c=midpoint(currentParking);parkingLot(current,c[0],c[1],Math.min(e.maxX-e.minX-10,85),Math.min(e.maxZ-e.minZ-10,60));}
 const subParking=new THREE.Group();future.add(subParking);parkingLot(subParking,cc[0],cc[1],Math.min(ce.maxX-ce.minX-10,115),70,-12,true);subParking.visible=false;const parkingLabel=label(future,'Despiece ilustrativo · aparcamiento bajo rasante',cc[0],cc[1],65,'parking','parking');const parkingItem=labelItems[labelItems.length-1];
 const parkLabels=[label(current,'Tívoli existente',pc[0],pc[1],45,'zone','park'),label(future,'01 · Parque de atracciones',pc[0],pc[1],55,'zone','park')];
 label(future,'02 · Ocio y comercio',cc[0],cc[1]+20,35,'zone','commercial');label(future,'Cubiertas y patios · infografía',cc[0],cc[1]-35,52,'small','park');label(future,'03 · Hotel',hc[0],hc[1],40,'zone','hotel');label(base,'EMABESA · referencia existente',uc[0],uc[1],20,'landmark','utility');

 // References and proposed roads use their actual traced paths.
 if(context){for(const r of context.railways||[]){ribbon(base,r.points,3,0x72837c,.2);line(base,r.points.map(([x,z])=>[x,.7,z]),0xe3d8bc)}for(const r of context.waterways||[])ribbon(base,r.points,2,0x7ca0ad,.2);}
 const cablecar=await buildCablecar({group:base,terrain,label});
 if(plan?.roads){for(const k of ['newCentralRoad','eastAccess','eastSouthRoad'])ribbon(future,plan.roads[k],9,0xddd5b9,1,'parking');ribbon(current,plan.roads.historicCentralRoad,7,0xb0b8b1,1,'parking');label(future,'Viario reordenado · avance',200,65,10,'small','parking')}
 for(const [key,color,id,title] of [['nursery',0xc7ab98,'utility','Equipamiento / guardería'],['socialEquipment',0xbca695,'utility','Asuntos sociales']]){if(plan?.[key]){poly(future,plan[key],color,1.2,0,id);const c=midpoint(plan[key]);if(key!=='cableCar')box(future,c[0],1,c[1],18,6,12,color,id);label(future,title,c[0],c[1],18,'landmark',id)}}
 const oldEdge=old.map(frontage.boundary);outline(current,oldEdge,0x9b7757,1.8);for(let i=0;i<old.length;i+=2)cyl(current,old[i][0],1,old[i][1],.3,3,0x8d795e);


 terrain.apply(base);terrain.apply(current);terrain.apply(future);
 const compass=document.createElement('div');compass.className='compass';compass.innerHTML='<b>↑</b><span>N</span>';host.appendChild(compass);
 let focusTarget=null,focusPosition=null;function reset(){focusTarget=new THREE.Vector3(55,0,-20);focusPosition=new THREE.Vector3(390,440,530)}reset();camera.position.copy(focusPosition);controls.target.copy(focusTarget);focusPosition=null;focusTarget=null;
 const targets={park:pc,commercial:cc,hotel:hc,green:midpoint(greens[0]),parking:cc,utility:uc,limits:[0,0],overview:[0,0],...existing.targets,...cablecar.targets,...proposal.targets};
 function focus(id){selected=id;if(id==='future-entry'){facadeView();return;}if(id==='attraction-3'||id==='existing-tower'){const p=targets[id];focusTarget=new THREE.Vector3(p[0],terrain.relative(...p)+28,p[1]);focusPosition=focusTarget.clone().add(new THREE.Vector3(78,54,105));return;}const p=targets[id]||[0,0];const far=['limits','overview'].includes(id);focusTarget=new THREE.Vector3(p[0],terrain.relative(p[0],p[1])+(id==='commercial'?8:0),p[1]);focusPosition=focusTarget.clone().add(new THREE.Vector3(far?490:(id.startsWith('existing-')||id.startsWith('attraction-')||id==='cablecar')?60:190,far?470:(id.startsWith('existing-')||id.startsWith('attraction-')||id==='cablecar')?72:220,far?650:(id.startsWith('existing-')||id.startsWith('attraction-')||id==='cablecar')?88:260));}
 function facadeView(){const p=proposal.targets?.['future-entry']||[50,130];focusTarget=new THREE.Vector3(p[0],terrain.relative(...p)+8,p[1]-45);focusPosition=new THREE.Vector3(p[0]+35,terrain.relative(...p)+105,p[1]+235);}
 const flight=installFlight(camera,controls,()=>{focusPosition=null;focusTarget=null});
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down=null;
 host.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();focusPosition=null;const d=camera.position.clone().sub(controls.target);if(e.key==='+'||e.key==='-')camera.position.copy(controls.target).add(d.multiplyScalar(e.key==='+'?.9:1.1));else{const shift=new THREE.Vector3(e.key==='ArrowLeft'?-15:e.key==='ArrowRight'?15:0,0,e.key==='ArrowUp'?-15:e.key==='ArrowDown'?15:0);camera.position.add(shift);controls.target.add(shift)}}});renderer.domElement.addEventListener('pointerdown',e=>{host.focus({preventScroll:true});down=[e.clientX,e.clientY];focusPosition=null;focusTarget=null});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),half=mode==='compare'?r.width/2:r.width,local=e.clientX-r.left,isCurrent=mode==='compare'?local<half:mode==='current';mouse.set(((local%half)/half)*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(pickables).filter(h=>{let o=h.object;while(o){if(o===current)return isCurrent;if(o===future)return !isCurrent;o=o.parent}return true});if(hits[0])onSelect(hits[0].object.userData.zone)});
 function renderView(x,w,h,isCurrent){current.visible=isCurrent;future.visible=!isCurrent;renderer.setViewport(x,0,w,h);renderer.setScissor(x,0,w,h);renderer.render(scene,camera)}
 function updateLabels(w,h){const occupied=[[],[]];const ordered=[...labelItems].sort((a,b)=> (a.id===selected?-10:b.id===selected?10:0)||({attraction:1,parking:0,existing:0,zone:0,small:1,landmark:2,north:0,street:3}[a.kind]??2)-({attraction:1,parking:0,existing:0,zone:0,small:1,landmark:2,north:0,street:3}[b.kind]??2));for(const item of ordered){item.el.hidden=true;item.twin.hidden=true;if(!labels||item.kind==='attraction'&&!attractionNames||item.kind==='parking'&&!parking)continue;const p=item.p.clone();p.y+=terrain.relative(p.x,p.z);p.project(camera);if(p.z>1||p.z< -1)continue;const half=mode==='compare'?w/2:w;const views=mode==='compare'?[0,1]:[mode==='current'?0:1];for(const v of views){if(item.g===current&&v!==0||item.g===future&&v!==1)continue;const offset=mode==='compare'?v*half:0,x=(p.x*.5+.5)*half+offset,y=(-p.y*.5+.5)*h;if(x<offset+18||x>offset+half-18||y<180||y>h-112)continue;const el=v===1&&mode==='compare'?item.twin:item.el;const bw=Math.min(230,item.el.textContent.length*(item.kind==='street'?4.7:5.6)+18),bh=item.kind==='street'?18:28;const rect=[x-bw/2,y-bh/2,x+bw/2,y+bh/2];if(rect[0]<offset+4||rect[2]>offset+half-4)continue;if(occupied[v].some(r=>rect[0]<r[2]+5&&rect[2]>r[0]-5&&rect[1]<r[3]+4&&rect[3]>r[1]-4))continue;occupied[v].push(rect);el.hidden=false;el.style.transform=`translate(-50%,-50%) translate(${x}px,${y}px)`;}}}

 const clock=new THREE.Clock();let frames=0,rideTime=0,previousTime=0,rideMotion=!matchMedia('(prefers-reduced-motion: reduce)').matches;function animate(){requestAnimationFrame(animate);const {width:w,height:h}=host.getBoundingClientRect();if(!w||!h)return;const sz=renderer.getSize(new THREE.Vector2());if(sz.x!==Math.floor(w)||sz.y!==Math.floor(h))renderer.setSize(w,h,false);camera.aspect=(mode==='compare'?w/2:w)/h;camera.zoom=(mode==='compare'?.64:1)*Math.min(1,w/720);camera.updateProjectionMatrix();if(focusPosition){camera.position.lerp(focusPosition,.07);controls.target.lerp(focusTarget,.07);if(camera.position.distanceTo(focusPosition)<.3){focusPosition=null;focusTarget=null}}controls.update();const t=clock.getElapsedTime();flight.update(t-previousTime);if(rideMotion&&mode!=='future')rideTime+=Math.min(.1,t-previousTime);previousTime=t;existing.update(rideTime);cablecar.update(t);for(const a of animated){if(a.g===current)continue;if(a.type==='wheel')a.o.rotation.z=t*.035;if(a.type==='train'){const u=a.motion.at(t),p=a.curve.getPointAt(u);p.y+=terrain.relative(p.x,p.z);a.o.position.copy(p);const next=a.curve.getPointAt((u+.001)%1);next.y+=terrain.relative(next.x,next.z);a.o.lookAt(next);}}
 renderer.setScissorTest(true);if(mode==='compare'){renderView(0,w/2,h,true);renderView(w/2,w/2,h,false)}else renderView(0,w,h,mode==='current');updateLabels(w,h);const n=new THREE.Vector3(controls.target.x,0,controls.target.z-100).project(camera),o=new THREE.Vector3(controls.target.x,0,controls.target.z).project(camera);compass.querySelector('b').style.transform=`rotate(${Math.atan2(n.x-o.x,n.y-o.y)}rad)`;frames++;}
 animate();return {setRideMotion(v){rideMotion=v},terrain,facadeView,setTerrain(v){terrain.setEnabled(v);proposal.updateTerrain();existing.updateTerrain()},profileView(){focusTarget=new THREE.Vector3(20,8,-30);focusPosition=new THREE.Vector3(490,150,30)},setMode(v){mode=v},focus,reset,top(){focusTarget=new THREE.Vector3(0,0,0);focusPosition=new THREE.Vector3(0,850,1)},setAerial(v){existing.setAerial(v)},setAttractionNames(v){attractionNames=v},setLabels(v){labels=v},setNight(v){night=v;scene.background.set(v?'#182b32':'#e7ece6');hemi.intensity=v?.7:2.3;sun.intensity=v?.8:1.8},setParking(v){parking=v;subParking.visible=v;if(v){subParking.position.y=45;focus('parking')}else subParking.position.y=0},screenshot(){const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;const ctx=c.getContext('2d');ctx.drawImage(renderer.domElement,0,0);const scale=c.width/host.clientWidth;ctx.scale(scale,scale);const h=host.clientHeight,w=host.clientWidth;ctx.fillStyle='#f7f6f0ee';ctx.fillRect(0,0,w,48);ctx.fillRect(0,h-38,w,38);ctx.fillStyle='#214939';ctx.font='bold 16px Arial';ctx.fillText('TÍVOLI · '+({future:'PROPUESTA',current:'EXISTENTE',compare:'EXISTENTE | PROPUESTA'}[mode]),18,29);ctx.font='11px Arial';ctx.fillText('Maqueta interpretativa · Avance 2025 · Arquitectura y atracciones ilustrativas · © OpenStreetMap contributors',18,h-15);return c.toDataURL('image/png')},info(){return {frames,context:!!context,plan:!!plan,existing:existing.counts,terrain:{source:terrain.data.source,enabled:terrain.enabled},cablecar:cablecar.metadata,objects:scene.children.length,mode}},renderer};
}
