import * as THREE from 'three';
import {TessellateModifier} from 'three/addons/modifiers/TessellateModifier.js';
export async function loadTerrain(){
 const r=await fetch('./terrain.json');if(!r.ok)throw Error('No se pudo cargar el modelo digital del terreno');const d=await r.json();
 const values=d.elevations,w=d.width,h=d.height;
 function elevation(x,z){const u=THREE.MathUtils.clamp((x-d.minX)/(d.maxX-d.minX)*(w-1),0,w-1),v=THREE.MathUtils.clamp((z-d.minZ)/(d.maxZ-d.minZ)*(h-1),0,h-1),a=Math.floor(u),b=Math.floor(v),c=Math.min(a+1,w-1),e=Math.min(b+1,h-1),fu=u-a,fv=v-b;return (values[b*w+a]*(1-fu)+values[b*w+c]*fu)*(1-fv)+(values[e*w+a]*(1-fu)+values[e*w+c]*fu)*fv;}
 const datum=d.originElevation??elevation(70,196);let enabled=true;const relative=(x,z)=>enabled?elevation(x,z)-datum:0;const changes=[];const basins=[];
 // Local modelled basins cut rendered ground only; survey elevations stay intact.
 function addBasin(points,level){basins.push({points,level});}
 function cutSurface(x,z,y){for(const {points,level} of basins){let inside=false,distance=Infinity;for(let i=0,j=points.length-1;i<points.length;j=i++){
 const a=points[j],b=points[i];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])inside=!inside;
 const dx=b[0]-a[0],dz=b[1]-a[1],t=THREE.MathUtils.clamp(((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz),0,1);distance=Math.min(distance,Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz));
 }const blend=inside?1:1-THREE.MathUtils.smoothstep(distance,1,4);y-=Math.max(0,y-level)*blend;}return y;}

 function apply(root,heightFn=relative){root.updateMatrixWorld(true);const skip=new Set();root.traverse(o=>{if(skip.has(o.parent)){skip.add(o);return}if(o.userData.fixedElevation){const pos=o.geometry.attributes.position,high=pos.array.slice(),old=high.slice();for(let i=0;i<pos.count;i++)old[i*3+1]-=relative(pos.getX(i),pos.getZ(i));changes.push({type:'geometry',o,old,high});return}if(o.isGroup&&Number.isFinite(o.userData.terrainLevel)){const old=o.position.y,delta=o.userData.terrainLevel;changes.push({type:'position',o,old,delta});o.position.y+=delta;skip.add(o);return}if(o.isGroup&&o!==root&&(Math.abs(o.position.x)+Math.abs(o.position.z)>1)){const p=o.getWorldPosition(new THREE.Vector3()),old=o.position.y,delta=heightFn(p.x,p.z);changes.push({type:'position',o,old,delta});o.position.y+=delta;skip.add(o);return}if(o.isInstancedMesh){const original=o.instanceMatrix.array.slice();const m=new THREE.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,m);const p=new THREE.Vector3().setFromMatrixPosition(m);m.elements[13]+=heightFn(p.x,p.z);o.setMatrixAt(i,m)}changes.push({type:'instance',o,old:original,high:o.instanceMatrix.array.slice()});o.instanceMatrix.needsUpdate=true;return}if(!o.geometry)return;
 let geom=o.geometry.clone();if(o.userData.drape&&geom.attributes.position.count<12000){geom=new TessellateModifier(5,9).modify(geom);}geom.computeBoundingBox();const center=geom.boundingBox.getCenter(new THREE.Vector3()).applyMatrix4(o.matrixWorld),rigid= !o.userData.drape&&!o.isLine&&!['TubeGeometry','PlaneGeometry','ShapeGeometry'].includes(geom.type);
 const inv=o.matrixWorld.clone().invert(),pos=geom.attributes.position,old=pos.array.slice(),vector=new THREE.Vector3(),delta=heightFn(center.x,center.z);
 for(let i=0;i<pos.count;i++){vector.fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld);const baseY=vector.y;vector.y+=rigid?delta:heightFn(vector.x,vector.z);if(o.userData.cutFill&&baseY<2)vector.y=relative(vector.x,vector.z)+baseY;if(o.userData.groundSurface)vector.y=cutSurface(vector.x,vector.z,vector.y);vector.applyMatrix4(inv);pos.setXYZ(i,vector.x,vector.y,vector.z)}geom.computeVertexNormals();geom.computeBoundingSphere();o.geometry=geom;changes.push({type:'geometry',o,old,high:pos.array.slice()});});}
 function ground(group){const geo=new THREE.PlaneGeometry(d.maxX-d.minX,d.maxZ-d.minZ,w-1,h-1);geo.rotateX(-Math.PI/2);geo.translate((d.minX+d.maxX)/2,-1.2,(d.minZ+d.maxZ)/2);const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0xd6ded2,roughness:1}));m.receiveShadow=true;m.userData.drape=true;m.userData.groundSurface=true;group.add(m);return m;}
 function setEnabled(v){enabled=v;for(const c of changes){if(c.type==='position')c.o.position.y=c.old+(v?c.delta:0);else if(c.type==='instance'){c.o.instanceMatrix.array.set(v?c.high:c.old);c.o.instanceMatrix.needsUpdate=true}else{c.o.geometry.attributes.position.array.set(v?c.high:c.old);c.o.geometry.attributes.position.needsUpdate=true;c.o.geometry.computeVertexNormals();c.o.geometry.computeBoundingSphere()}}}
 return {data:d,datum,elevation,relative,apply,ground,addBasin,setEnabled,get enabled(){return enabled}};
}
